[package]
name = "solana-leader-precached"
version = "0.1.0"
edition = "2021"
workspace = "../agave-arm64-engine/agave-src"

[dependencies]
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
solana-clock = { workspace = true }
solana-epoch-schedule = { workspace = true }
solana-leader-schedule = { workspace = true }
solana-pubkey = { workspace = true }
solana-runtime = { workspace = true }
solana-vote = { workspace = true, features = ["dev-context-only-utils"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
assert_matches = { workspace = true }
solana-vote = { workspace = true, features = ["dev-context-only-utils"] }
